services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=example
    networks:
      - finalproject
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./utils/init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: .
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=example
      - DB_NAME=todo
    ports:
      - 80:3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - finalproject

networks:
  finalproject:
    name: finalprojectnetwork
